language: ruby
rvm:
  - 2.5.1
branches:
  only:
    - master
install: bundle install
script: bundle exec jekyll b
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./_site
  repo: Sheffield-Digital-Leadership-Meetup/sheffield-digital-leadership-meetup.github.io
  target-branch: master
  on:
    branch: master
